spring:
  application:
    name: zuul
server:
  port: 8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

zuul:
  routes:
    produto:
      serviceId: produto
      path: /api/produto/**

    itens:
      serviceId: item
      path: /api/itens/**

    usuarios:
      serviceId: usuarios
      path: /api/usuarios/**
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon:
#  ConnectTimeout: 3000
#  ReadTimeout: 10000